### ISSUE TITLE
Node must be updated to run leaderboard-mocha

### ISSUE THREAD

**Issue by lc3t35** [meteor-velocity/velocity-examples#29]
see https://github.com/meteor-velocity/node-soft-mirror/issues/15#issuecomment-68396433

Works fine after these steps
````
$ npm install -g n
$ n 0.10.29
$ node --version
v0.10.29
````

**Comment by zda** [comment]
+1, except mine was asking for 0.10.33.

**Comment by Sanjo** [comment]
@rissem Can you update the soft-mirror dependency in mike:mocha to the latest version. This problem is fixed since 0.2.8.
