### ISSUE TITLE
Multi-app repo structure is confusing

### ISSUE THREAD

**Issue by zda** [meteor-velocity/velocity-examples#30]
http://velocity.meteor.com/getting-started indicates that you should just run `meteor` in the project root, and the `/.meteor` folder suggests it's a Meteor app, but this fails, at least as of 1.0.2.1. Perhaps the docs could be updated.

**Comment by samhatoum** [comment]
I'm confused :) what do you mean?

**Comment by Sanjo** [comment]
Thanks for notifying us about this issue.

To fix:

* [ ] https://github.com/meteor-velocity/velocity-examples/tree/master/.meteor should be removed.
* [ ] The instruction at http://velocity.meteor.com/getting-started#seeanexample is wrong.

**Comment by ryw** [comment]
PR to fix doc submitted https://github.com/meteor-velocity/velocity-website/pull/14

**Comment by Sanjo** [comment]
Thanks.
