### ISSUE TITLE
leaderboard-fixture.js in root directory of cucumber example

### ISSUE THREAD

**Issue by ryw** [meteor-velocity/velocity-examples#31]
@samhatoum I'm curious why you put it in root directory rather than within the /tests directory? I'd probably move the file to /cucumber/features/support/fixtures.js — I know I can do what I'd like in my own projects, just curious if you had a reason for keeping it outside the test directory?

**Comment by samhatoum** [comment]
This was before we had the `test-proxy` package working. It will now work if you put it in `/tests`

**Comment by samhatoum** [comment]
good catch

**Comment by ryw** [comment]
Yeah I tested and saw it worked — I'll PR and move it there if you like the name + spot I chose :)

**Comment by samhatoum** [comment]
I wouldn't put it under support though, conceivably you could use the same fixture from integration tests using jasmine (for example)

**Comment by samhatoum** [comment]
PR welcome! Thanks
