### ISSUE TITLE
Nightwatch hangs up after firefox launches

### ISSUE THREAD

**Issue by JoshDellay** [meteor-velocity/velocity-examples#36]
I am trying to run the velocity example of nightwatch and can't seem to get the examples to work for the life of me... Mocha & Jasmine seems to do ok but Cucumber & Nightwatch are out of the question... here's what my terminal shows after starting the run_nightwatch.sh:

sudo ./run_nightwatch.sh
Setting variables...
Checking user defined options...

Parsing options...
Changing file permissions...
Looking for Nightwatch executables...
  installing nightwatch in .meteor/local/build
nightwatch@0.5.36 node_modules/nightwatch
├── mkpath@0.1.0
├── ejs@0.8.8
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── grunt@0.4.5 (which@1.0.8, dateformat@1.0.2-1.2.3, eventemitter2@0.4.14, getobject@0.1.0, rimraf@2.2.8, colors@0.6.2, async@0.1.22, hooker@0.2.3, grunt-legacy-util@0.2.0, exit@0.1.2, nopt@1.0.10, lodash@0.9.2, coffee-script@1.3.3, underscore.string@2.2.1, iconv-lite@0.2.11, glob@3.1.21, findup-sync@0.1.3, grunt-legacy-log@0.1.1, js-yaml@2.0.5)
Stitching together command to run: .meteor/local/build/node_modules/nightwatch/bin/nightwatch -e default -c .meteor/local/build/programs/server/assets/packages/clinical_nightwatch/nightwatch_from_app_root.json
Running Nightwatch...

Starting selenium server... started - PID:  37239

[Walkthrough] Test Suite
========================

Running:  Basic Nightwatch Walkthrough

After this shell script starts a firefox browser is launched but shows nothing but a blank white screen.  Any suggestions on how to get past this step?

**Comment by awatson1978** [comment]
Hi Josh!  
Sorry to hear this isn't working for you!  The fact that you're getting Firefox to launch is a good sign.  Could you check that you're using Firefox 31?

**Comment by JoshDellay** [comment]
Ahh, yes that did the trick. I was on 35.0 an downgraded to 31 and it worked.  It did spit out 1 error at the end related to logging, Error writing log file to: logs/selenium-debug.log which I'll take a look at.

Side question, is it possible to use this framework on a server environment without a display like Ubuntu Server 14.0.4 or should I be looking somewhere else for that?

**Comment by awatson1978** [comment]
Glad to hear.  :)

Just create logs file in your project, and you should be good to go with the logging.  

You may want to look at [the install script for Travis CI integration](https://github.com/awatson1978/clinical-nightwatch#travis-continuous-integration--).  It's also possible to set up Selenium and Nightwatch to use PhantomJS, but we haven't gotten that working quite yet.

**Comment by JoshDellay** [comment]
Thanks for the replies, ill take a look.  Also thanks for all the hard work on velocity and framework integration for meteor keep it up!
