### ISSUE TITLE
Deprecation notices and two errors, missing methods

### ISSUE THREAD

**Issue by mrmowgli** [meteor-velocity/velocity-examples#42]
Lots of deprecation notices running the leaderboard-jasmine example, and two errors in Chrome console.

    W20150409-15:04:12.483(-7) (blaze.js:71) Warning: Assigning helper with `Template.leaderboard.players = ...` is deprecated.  Use `Template.leaderboard.helpers(...)` instead.
    logging.js:65 W20150409-15:04:12.496(-7) (blaze.js:71) Warning: Assigning helper with `Template.player.selected = ...` is deprecated.  Use `Template.player.helpers(...)` instead.
    logging.js:65 W20150409-15:04:12.509(-7) (blaze.js:71) Warning: Assigning helper with `Template.leaderboard.selected_name = ...` is deprecated.  Use `Template.leaderboard.helpers(...)` instead.
    logging.js?07e201b648f16be8435a4f666156995eeda0c750:100 W20150409-15:04:13.187(-7) (blaze.js:71) Warning: Assigning helper with `Template.leaderboard.players = ...` is deprecated.  Use `Template.leaderboard.helpers(...)` instead.
    logging.js?07e201b648f16be8435a4f666156995eeda0c750:100 W20150409-15:04:13.198(-7) (blaze.js:71) Warning: Assigning helper with `Template.leaderboard.selected_name = ...` is deprecated.  Use `Template.leaderboard.helpers(...)` instead.
    logging.js?07e201b648f16be8435a4f666156995eeda0c750:100 W20150409-15:04:13.224(-7) (blaze.js:71) Warning: Assigning helper with `Template.player.selected = ...` is deprecated.  Use `Template.player.helpers(...)` instead.
    sanjo_jasmine.js?91583a1f92d48ad01132b9f6aec503cb3b6b297a:4180 [sanjo:jasmine]: Running Jasmine tests
    4
    meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:887 Error invoking Method 'jasmine/specDoneConsumer': Method not found [404]
    meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:887 Error invoking Method 'jasmine/doneConsumer': Method not found [404]

**Comment by Sanjo** [comment]
Thanks for bringing up this issue. I will update the example soon.

**Comment by Sanjo** [comment]
I've fixed the deprecation warnings and updated the example to the latest versions.
