### ISSUE TITLE
Can we run the 5-test example in under 30 seconds ?

### ISSUE THREAD

**Issue by deanius** [meteor-velocity/velocity-examples#48]
MacBook Pro Retina 15 (Mid 2015), full SSD, and I can't run the CLI on an example in under 30 sec ? 

This is much slower than I expect command line tests to be. Have you any knowledge why ? Something written in Vows, for example, can be near instantaneous.

```
~/src/velocity-examples/leaderboard-mocha (master) $ time meteor --test
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
=> A patch (Meteor 1.2.0.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
I20151009-22:41:11.435(-5)? [velocity] mocha is starting a mirror at http://localhost:56069/.
I20151009-22:41:11.436(-5)? [velocity] You can see the mirror logs at: tail -f /Users/deanius/src/velocity-examples/leaderboard-mocha/.meteor/local/log/mocha.log
PASSED mocha : Select Grace Hopper => should show Grace the inside div class='name' (above the give points button)
PASSED mocha : Select Grace Hopper => should highlight Grace's name
PASSED mocha : Server initialization => should insert players into the database after server start
PASSED mocha : Point Assignment => should give a player 5 points when they are selected and the button is pressed
PASSED mocha : Player Ordering => should result in a list where the first player has as many or more points than the second player
TESTS RAN SUCCESSFULLY

real	0m32.659s
user	0m8.700s
sys	0m0.620s
```

**Comment by Sanjo** [comment]
The building and starting of the testing mirror has a relative huge overhead. Executing the tests is as fast as it would be with any other system.

In sanjo:jasmine the client unit mode is also very fast (it does not use a mirror).

Further optimizations will be made in the future if we find the resources to do it. If you are interested in sponsoring this improvements, let us know. More info on http://xolv.io/velocity-premium-support/. Xolv.io is a startup and we have very limited resources ;-)

**Comment by deanius** [comment]
This is a comparatively poor testing experience, relative to other frameworks, and it's still the case a year after I started looking for good testing support from Meteor. As to why between MDG and the people who've built testing tools around it like yourselves, this is still the case, I don't know. But enough of that, because we have a hackathon to get to today!
