### ISSUE TITLE
testing the publish and subscribe

### ISSUE THREAD

**Issue by binarytracer** [meteor-velocity/velocity-examples#49]
hi @Sanjo, is that possible to test the Meteor.publish and Meteor.subscribe?

**Comment by Sanjo** [comment]
Yes.

1. Setup some data in your database
2. Subscribe to a publication in your test
3. Check that your collection contains the expected data
4. Unsubscribe from the publication

**Comment by binarytracer** [comment]
it appears that this testing will only possible on client/integration right?

**Comment by binarytracer** [comment]
if possible can you show some code examples? thanks

**Comment by markoshust** [comment]
it would be nice to know how to use subscribe inside a client integration test... i'm a bit lost as well

**Comment by Sanjo** [comment]
Generally you do it in the same way as in app code. You also need to:

* Wait until the data is available on the client, before running the test that depends on subscription data.
* Stop the subscription after the test.

Roughly like that:

```
beforeEach(function () {
  this.subscription = Meteor.subscribe('...');
});

beforeEach(function (done) {
  var expectedDataEntities = 9;
  Tracker.autorun(function (computation) {
    if (MyCollection.find().count() === expectedDataEntities) {
      computation.stop();
      done();
    }
  });
});

afterEach(function () {
  this.subscription.stop();
});
```

I personally don't need to subscribe to any data in the tests that I write for our app. Instead I use local collections and just insert data with collection.insert.
