### ISSUE TITLE
Question about the examples:

### ISSUE THREAD

**Issue by robvanpamel** [meteor-velocity/velocity-examples#50]
Hi, 

I'm very new to Meteor and velocity so it would be a lucky shot if it is a real issue. 
However in 
https://github.com/meteor-velocity/velocity-examples/blob/master/leaderboard-jasmine/leaderboard.js 
line 79, wouldn't it be better ( best practice) to return the PlayersService.getPlayerList iso Players.find? 

Or should i create a pull request? 

Kind regards
  Rob

**Comment by ghost** [comment]
I don't really have a strong opinion for any of the both options. Both works. And Meteor publications are coupled to Collections.Cursor anyway.
