### ISSUE TITLE
Where to define where Jasmine can find the source code in the tests

### ISSUE THREAD

**Issue by robvanpamel** [meteor-velocity/velocity-examples#52]
Hi,

I wonder how Velocity / Jasmine knows where it can find the source files. 
I have some classes defined which i want to test, but i can't figure out how I can configure where they are located. Or is this a convention from Jasmine? If i look at the Jasmine documentation, you can specify it in the SpecRunner.html. However i can't find this kind of file for velocity. 

My folder structure is like this
- client 
- server
  - services
    - serviceA.js
- tests
  - jasmine
    - server
      - unit
        - services
          - serviceASpec.js

Kind regards
  Rob

**Comment by ghost** [comment]
The folders are currently not configurable. See https://meteor-testing.readme.io/docs/jasmine-testing-modes. You want to put your server unit tests into the tests/jasmine/server/integration folder though.
I will soon look into how unit testing will best work with Meteor 1.3.

**Comment by robvanpamel** [comment]
hmm, it is still not working. I must be doing something wrong. Do you have to put a package.js file where you specify your tests? 
Perhaps you can take a look at my code which is hosted on github.

The code that i want to test is here: 
https://github.com/robvanpamel/coderepository/blob/master/meteor/sandwich-app/server/Services/SandwichService.js 

The unit Test is here: 
https://github.com/robvanpamel/coderepository/blob/master/meteor/sandwich-app/tests/jasmine/server/integration/spec/SandwichServiceSpec.js 
When I uncomment the created SandwichService in the Unit Test, the test works, which is normal. 

I haven't done any configuration elsewhere in meteor, and i think that is the problem. 
How can Jasmine know where it can find the SandwichService I'm trying to test? It is also the error i get. 
  "ReferenceError: SandwichesService is not defined "

Could you help me out ?

Kind regards and thanks upfront! 
  Rob

**Comment by ghost** [comment]
The problem is that `function SandwichesService(){};` does not create a global. Write `SandwichesService = function SandwichesService(){};` instead. After this your tests should work.

> How can Jasmine know where it can find the SandwichService I'm trying to test?

The whole application is loaded before the tests are executed. The tests run in the application context. So everything is available, that is available in your app.
